# Generated by Django 5.0 on 2024-04-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
    ]
