# Generated by Django 5.0 on 2024-04-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixio', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
